version: 2
updates:
  - package-ecosystem: "github-actions"
    assignees: ["blixten85"]
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/Stockholm"
    groups:
      actions-patch-minor:
        update-types: ["minor", "patch"]

  - package-ecosystem: "npm"
    assignees: ["blixten85"]
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:10"
      timezone: "Europe/Stockholm"
    groups:
      npm-patch-minor:
        update-types: ["minor", "patch"]
