name: Dependabot queue events

on:
  schedule:
    - cron: '41 * * * *'
  workflow_dispatch:

permissions: {}

jobs:
  queue:
    uses: Avkroken/.github/.github/workflows/dependabot-automerge.yml@8c05288325c7646972c4c6ba0d4493a84152d7d8
    secrets:
      app-private-key: ${{ secrets.GAMNACKEN_PRIVATE_KEY }}
