name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions: {}

jobs:
  release:
    uses: Avkroken/.github/.github/workflows/release-please.yml@abfaf7aae8a69f1dfa6bc7e01440496edb59def6
    secrets:
      app-private-key: ${{ secrets.GAMNACKEN_PRIVATE_KEY }}
